UPDATE exercises SET name = 'hiperextensja' WHERE exercise_id = 122;
UPDATE exercises SET name = 'hiperextensja (na ławce)' WHERE exercise_id = 123;
UPDATE exercises SET name = 'skok w dolną część pleców' WHERE exercise_id = 165;
UPDATE exercises SET name = 'sphinx' WHERE exercise_id = 273;
UPDATE exercises SET name = 'rozciąganie kręgosłupa' WHERE exercise_id = 275;
UPDATE exercises SET name = 'stanie z miednicą w przód' WHERE exercise_id = 286;
UPDATE exercises SET name = 'dwuręczne chwytanie palców stóp (mężczyzna)' WHERE exercise_id = 311;
UPDATE exercises SET name = 'pies do góry patrzący' WHERE exercise_id = 313;
UPDATE exercises SET name = 'dźwignia wznoszenia tułowia' WHERE exercise_id = 494;
UPDATE exercises SET name = 'wznoszenie tułowia na piłce do ćwiczeń' WHERE exercise_id = 592;
UPDATE exercises SET name = 'wznoszenie tułowia na piłce do ćwiczeń z wyciągniętymi rękoma' WHERE exercise_id = 597;
UPDATE exercises SET name = 'wznoszenie tułowia na piłce do ćwiczeń z rękoma za głową' WHERE exercise_id = 598;
UPDATE exercises SET name = 'wznoszenie tułowia na piłce do ćwiczeń z uniesionymi kolanami' WHERE exercise_id = 599;
UPDATE exercises SET name = 'wznoszenie tułowia na piłce do ćwiczeń z obrotem' WHERE exercise_id = 600;
UPDATE exercises SET name = 'przytulanie piłki do ćwiczeń' WHERE exercise_id = 603;
UPDATE exercises SET name = 'wznoszenie nóg na piłce do ćwiczeń w pozycji leżącej na brzuchu' WHERE exercise_id = 610;
UPDATE exercises SET name = 'prosty wyprost nóg na opasce oporowej' WHERE exercise_id = 666;
UPDATE exercises SET name = 'hiperextensja z obciążeniem (na piłce do ćwiczeń)' WHERE exercise_id = 1225;
UPDATE exercises SET name = 'rozciąganie pleców na wałku' WHERE exercise_id = 1260;
