UPDATE exercises SET name = 'skoki na szerokość (mężczyzna)' WHERE exercise_id = 13;
UPDATE exercises SET name = 'krok w przód i w tył' WHERE exercise_id = 14;
UPDATE exercises SET name = 'chód na czworaka' WHERE exercise_id = 20;
UPDATE exercises SET name = 'burpee' WHERE exercise_id = 46;
UPDATE exercises SET name = 'półprzygibanie na kolana (mężczyzna)' WHERE exercise_id = 105;
UPDATE exercises SET name = 'bieg na miejscu na wysokie kolana' WHERE exercise_id = 119;
UPDATE exercises SET name = 'burpee z podskokami' WHERE exercise_id = 145;
UPDATE exercises SET name = 'podskoki (mężczyzna)' WHERE exercise_id = 146;
UPDATE exercises SET name = 'wspinaczka górska' WHERE exercise_id = 177;
UPDATE exercises SET name = 'pchnięcie do biegu' WHERE exercise_id = 205;
UPDATE exercises SET name = 'bieg' WHERE exercise_id = 228;
UPDATE exercises SET name = 'bieg (sprzęt)' WHERE exercise_id = 229;
UPDATE exercises SET name = 'skoki nożycowe (mężczyzna)' WHERE exercise_id = 235;
UPDATE exercises SET name = 'półprzysiad skoczny (mężczyzna)' WHERE exercise_id = 246;
UPDATE exercises SET name = 'krótki bieg z małymi kroczkami' WHERE exercise_id = 247;
UPDATE exercises SET name = 'kroki wskakujące jak łyżwiarz' WHERE exercise_id = 270;
UPDATE exercises SET name = 'skok na nartach' WHERE exercise_id = 271;
UPDATE exercises SET name = 'skok gwiazdą (mężczyzna)' WHERE exercise_id = 288;
UPDATE exercises SET name = 'obrót 360 stopni' WHERE exercise_id = 299;
UPDATE exercises SET name = 'chód z uniesionymi kolanami i wysokimi krokami' WHERE exercise_id = 316;
UPDATE exercises SET name = 'bieg na kole' WHERE exercise_id = 318;
UPDATE exercises SET name = 'rower treningowy' WHERE exercise_id = 490;
UPDATE exercises SET name = 'chód na stacjonarnym rowerze' WHERE exercise_id = 562;
UPDATE exercises SET name = 'chód po nachyleniu na bieżni' WHERE exercise_id = 563;
UPDATE exercises SET name = 'skok na skakance' WHERE exercise_id = 831;
UPDATE exercises SET name = 'burpee z hantlami' WHERE exercise_id = 862;
UPDATE exercises SET name = 'bieg na stacjonarnym rowerze wersja 3' WHERE exercise_id = 1320;
UPDATE exercises SET name = 'chód na stacjonarnym elliptical cross trainer' WHERE exercise_id = 1323;
UPDATE exercises SET name = 'chód na schodkowym stepmillu' WHERE exercise_id = 1324;
