UPDATE exercises SET name = 'biceps koncentryczny uginacz nóg' WHERE exercise_id = 26;
UPDATE exercises SET name = 'wąskie podciąganie na biceps' WHERE exercise_id = 27;
UPDATE exercises SET name = 'podciąganie na biceps' WHERE exercise_id = 28;
UPDATE exercises SET name = 'uginanie bicepsa na boku własnego ciała' WHERE exercise_id = 33;
UPDATE exercises SET name = 'uginanie na wyciągu z wąskim uchwytem' WHERE exercise_id = 332;
UPDATE exercises SET name = 'koncentryczne uginanie na wyciągu' WHERE exercise_id = 333;
UPDATE exercises SET name = 'uginanie na wyciągu' WHERE exercise_id = 338;
UPDATE exercises SET name = 'cable drag curl' WHERE exercise_id = 344;
UPDATE exercises SET name = 'uginanie młotkowe na wyciągu (z użyciem liny)' WHERE exercise_id = 349;
UPDATE exercises SET name = 'leżące uginanie na wyciągu na biceps' WHERE exercise_id = 370;
UPDATE exercises SET name = 'uginanie na dźwigni na biceps' WHERE exercise_id = 496;
UPDATE exercises SET name = 'uginanie siedzące na biceps (na piłce stabilizującej)' WHERE exercise_id = 591;
UPDATE exercises SET name = 'zmiennie uginanie na biceps opaską' WHERE exercise_id = 620;
UPDATE exercises SET name = 'koncentryczne uginanie na opaskę' WHERE exercise_id = 629;
UPDATE exercises SET name = 'uginanie jednoręczne na biceps nad głową z opaską' WHERE exercise_id = 641;
UPDATE exercises SET name = 'zmiennie uginanie na biceps sztangą' WHERE exercise_id = 674;
UPDATE exercises SET name = 'uginanie na biceps sztangą (z ortezą na ramiona)' WHERE exercise_id = 680;
UPDATE exercises SET name = 'uginanie na biceps sztangą' WHERE exercise_id = 684;
UPDATE exercises SET name = 'uginanie na biceps sztangą z przyciąganiem' WHERE exercise_id = 692;
UPDATE exercises SET name = 'uginanie na biceps sztangą leżąc' WHERE exercise_id = 724;
UPDATE exercises SET name = 'zmiennie uginanie na biceps hantlami' WHERE exercise_id = 839;
UPDATE exercises SET name = 'zmiennie uginanie na biceps hantlami (z ortezą na ramiona)' WHERE exercise_id = 840;
UPDATE exercises SET name = 'zmiennie uginanie młotkowe na biceps hantlami' WHERE exercise_id = 841;
UPDATE exercises SET name = 'zmiennie uginanie na biceps hantlami' WHERE exercise_id = 842;
UPDATE exercises SET name = 'uginanie koncentryczne na biceps ze sztangą łamaną' WHERE exercise_id = 1136;
UPDATE exercises SET name = 'uginanie koncentryczne na biceps ze sztangą łamaną w uchwycie blisko ciała' WHERE exercise_id = 1139;
UPDATE exercises SET name = 'uginanie koncentryczne na biceps ze sztangą łamaną' WHERE exercise_id = 1140;
UPDATE exercises SET name = 'uginanie koncentryczne na biceps ze sztangą łamaną' WHERE exercise_id = 1141;
UPDATE exercises SET name = 'podnoszenie kettlebell od spodu z pozycji wiszącej' WHERE exercise_id = 1179;
UPDATE exercises SET name = 'dwuręczne podnoszenie kettlebell od spodu na zmianę' WHERE exercise_id = 1180;
UPDATE exercises SET name = 'uginanie młotkowe sztangi olimpijskiej' WHERE exercise_id = 1212;
UPDATE exercises SET name = 'uginanie na stojąco z obciążeniem' WHERE exercise_id = 1241;
UPDATE exercises SET name = 'uginanie na biceps opaską w pozycji siedzącej' WHERE exercise_id = 1255;
UPDATE exercises SET name = 'uginanie na biceps na maszynie Smitha' WHERE exercise_id = 1289;

