UPDATE exercises SET name = 'Kręgi w kostkach' WHERE exercise_id = 6;
UPDATE exercises SET name = 'Podnoszenie ciężaru ciała na mięśniach łydek w staniu' WHERE exercise_id = 36;
UPDATE exercises SET name = 'Skok na skrzynię w dół z ustabilizowaniem jednej nogi' WHERE exercise_id = 44;
UPDATE exercises SET name = 'Rozciąganie łydek z oparciem rąk o ścianę' WHERE exercise_id = 49;
UPDATE exercises SET name = 'Rozciąganie łydek z oparciem rąk o ścianę' WHERE exercise_id = 50;
UPDATE exercises SET name = 'Ruchy okrężne kolana' WHERE exercise_id = 60;
UPDATE exercises SET name = 'Wspięcia na palcach stojąc na plecach osła' WHERE exercise_id = 78;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie stojąc na jednej nodze' WHERE exercise_id = 446;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie stojąc na jednej nodze' WHERE exercise_id = 455;
UPDATE exercises SET name = 'Nacisk na łydki na maszynie' WHERE exercise_id = 497;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie leżąc na brzuchu osła' WHERE exercise_id = 502;
UPDATE exercises SET name = 'Ruchy okrężne łydek na maszynie' WHERE exercise_id = 533;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie siedząc na łydkach' WHERE exercise_id = 534;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie siedząc na łydkach' WHERE exercise_id = 535;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie siedząc na łydkach na maszynie do wyciskania nóg' WHERE exercise_id = 549;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie stojąc na łydkach' WHERE exercise_id = 554;
UPDATE exercises SET name = 'Wspomagane rozciąganie mięśni łydek leżąc' WHERE exercise_id = 566;
UPDATE exercises SET name = 'Podnoszenie ciężaru na jednej nodze na taśmie' WHERE exercise_id = 655;
UPDATE exercises SET name = 'Podnoszenie ciężaru na jednej nodze na taśmie w odwrotnym kierunku' WHERE exercise_id = 656;
UPDATE exercises SET name = 'Podnoszenie ciężaru na obie nogi na taśmie (taśma pod obiema nogami) v. 2' WHERE exercise_id = 668;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie leżąc na brzuchu' WHERE exercise_id = 693;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie siedząc na łydkach' WHERE exercise_id = 763;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie siedząc na łydkach' WHERE exercise_id = 764;
UPDATE exercises SET name = 'Rozciąganie łydek z użyciem liny' WHERE exercise_id = 829;
UPDATE exercises SET name = 'Rozciąganie mięśni strzałkowych' WHERE exercise_id = 833;
UPDATE exercises SET name = 'Rozciąganie mięśni piszczelowych tylnych' WHERE exercise_id = 834;
UPDATE exercises SET name = 'Podnoszenie ciężaru siedząc na łydkach z hantlami' WHERE exercise_id = 1045;
UPDATE exercises SET name = 'Podnoszenie ciężaru siedząc na jednej nodze na łydkach z hantlami' WHERE exercise_id = 1057;
UPDATE exercises SET name = 'Podnoszenie ciężaru siedząc na jednej nodze na łydkach z hantlami (chwyt młotkowy)' WHERE exercise_id = 1058;
UPDATE exercises SET name = 'Podnoszenie ciężaru siedząc na jednej nodze na łydkach z hantlami (chwyt dłonią do góry)' WHERE exercise_id = 1059;
UPDATE exercises SET name = 'Podnoszenie ciężaru na jednej nodze na łydkach z hantlami' WHERE exercise_id = 1072;
UPDATE exercises SET name = 'Podnoszenie ciężaru stojąc na łydkach z hantlami' WHERE exercise_id = 1086;
UPDATE exercises SET name = 'Podnoszenie ciężaru na piłce ćwiczeń przy ścianie' WHERE exercise_id = 1123;
UPDATE exercises SET name = 'Podnoszenie ciężaru na piłce ćwiczeń przy ścianie (tenisowa piłka między kostkami)' WHERE exercise_id = 1124;
UPDATE exercises SET name = 'Podnoszenie ciężaru na piłce ćwiczeń przy ścianie (tenisowa piłka między kolanami)' WHERE exercise_id = 1125;
UPDATE exercises SET name = 'Podnoszenie ciężaru na jednej nodze (na hantlu)' WHERE exercise_id = 1130;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie do wyciskania nóg' WHERE exercise_id = 1155;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie do wyciskania nóg na jednej nodze' WHERE exercise_id = 1156;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie do wyciskania nóg na jednej nodze' WHERE exercise_id = 1158;
UPDATE exercises SET name = 'Nacisk na łydki na maszynie Smitha' WHERE exercise_id = 1163;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie Smitha na jednej nodze na podłodze' WHERE exercise_id = 1165;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie Smitha w odwrotnym kierunku' WHERE exercise_id = 1167;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie Smitha w odwrotnym kierunku' WHERE exercise_id = 1169;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie Smitha siedząc na jednej nodze' WHERE exercise_id = 1220;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie Smitha stojąc na jednej nodze' WHERE exercise_id = 1295;
UPDATE exercises SET name = 'Podnoszenie ciężaru na maszynie Smitha na palcach' WHERE exercise_id = 1297;
