UPDATE equipment_type SET category = 'Wielofunkcyjny’', name = 'własna waga ciała' WHERE equipment_id = 41;
UPDATE equipment_type SET category = 'Cardio', name = 'wyciąg' WHERE equipment_id = 42;
UPDATE equipment_type SET category = 'Siła', name = 'maszyna dźwigniowa' WHERE equipment_id = 43;
UPDATE equipment_type SET category = 'Wielofunkcyjny’', name = 'z pomocą' WHERE equipment_id = 44;
UPDATE equipment_type SET category = ' Rehabilitacyjny', name = 'miękka piłka lekarska' WHERE equipment_id = 45;
UPDATE equipment_type SET category = 'Siła', name = 'piłka stabilizująca' WHERE equipment_id = 46;
UPDATE equipment_type SET category = 'Siła', name = 'opaska oporowa' WHERE equipment_id = 47;
UPDATE equipment_type SET category = 'Siła', name = 'sztanga' WHERE equipment_id = 48;
UPDATE equipment_type SET category = 'Siła', name = 'sznur' WHERE equipment_id = 49;
UPDATE equipment_type SET category = 'Siła', name = 'hantla' WHERE equipment_id = 50;
UPDATE equipment_type SET category = 'Siła', name = 'sztanga łamana EZ' WHERE equipment_id = 51;
UPDATE equipment_type SET category = 'Siła', name = 'maszyna na prowadzeniu' WHERE equipment_id = 52;
UPDATE equipment_type SET category = 'Cardio', name = 'ergometr górny korpus' WHERE equipment_id = 53;
UPDATE equipment_type SET category = 'Cardio', name = 'kettlebell' WHERE equipment_id = 54;
UPDATE equipment_type SET category = 'Siła', name = 'sztanga olimpijska' WHERE equipment_id = 55;
UPDATE equipment_type SET category = 'Cardio', name = 'z obciążeniem' WHERE equipment_id = 56;
UPDATE equipment_type SET category = 'Cardio', name = 'piłka Bosu' WHERE equipment_id = 57;
UPDATE equipment_type SET category = 'Siła', name = 'opaska oporowa' WHERE equipment_id = 58;
UPDATE equipment_type SET category = 'Siła', name = 'wałek' WHERE equipment_id = 59;
UPDATE equipment_type SET category = 'Siła', name = 'maszyna skierg' WHERE equipment_id = 60;
UPDATE equipment_type SET category = 'Siła', name = 'młot' WHERE equipment_id = 61;
UPDATE equipment_type SET category = 'Cardio', name = 'maszyna Smitha' WHERE equipment_id = 62;
UPDATE equipment_type SET category = ' Rehabilitacyjny', name = 'wałek' WHERE equipment_id = 63;
UPDATE equipment_type SET category = 'Siła', name = 'rower stacjonarny' WHERE equipment_id = 64;
UPDATE equipment_type SET category = 'Cardio', name = 'opona' WHERE equipment_id = 65;
UPDATE equipment_type SET category = 'Siła', name = 'drążek pułapkowy' WHERE equipment_id = 66;
UPDATE equipment_type SET category = 'Siła', name = 'maszyna eliptyczna' WHERE equipment_id = 67;
UPDATE equipment_type SET category = 'Cardio', name = 'maszyna stepmill' WHERE equipment_id = 68;
