UPDATE exercises SET name = 'chwyt za nogi w kierunku palców (mężczyzna)' WHERE exercise_id = 11;
UPDATE exercises SET name = 'podstawowy chwyt za palce stóp (mężczyzna)' WHERE exercise_id = 19;
UPDATE exercises SET name = 'wyprost bioder na ławce' WHERE exercise_id = 23;
UPDATE exercises SET name = 'skręt na leżąco z wygiętymi kolanami (mężczyzna)' WHERE exercise_id = 25;
UPDATE exercises SET name = 'płaski skok na nogi z obciążeniem własnego ciała' WHERE exercise_id = 30;
UPDATE exercises SET name = 'przysiad żurawia' WHERE exercise_id = 72;
UPDATE exercises SET name = 'płaski kopniak' WHERE exercise_id = 88;
UPDATE exercises SET name = 'deadlift na wyciągu' WHERE exercise_id = 339;
UPDATE exercises SET name = 'przeciągnięcie na wyciągu (z użyciem liny)' WHERE exercise_id = 397;
UPDATE exercises SET name = 'wyprost bioder na wyciągu stojąc' WHERE exercise_id = 451;
UPDATE exercises SET name = 'deadlift na dźwigni' WHERE exercise_id = 500;
UPDATE exercises SET name = 'wyprost bioder na dźwigni w wersji 2' WHERE exercise_id = 509;
UPDATE exercises SET name = 'dźwignia w poziomie na jednej nodze' WHERE exercise_id = 510;
UPDATE exercises SET name = 'odwrotny hiper wyprostowania na dźwigni' WHERE exercise_id = 531;
UPDATE exercises SET name = 'siedzące dzień dobry na dźwigni' WHERE exercise_id = 541;
UPDATE exercises SET name = 'wspomagane rozciąganie pośladków na leżąco' WHERE exercise_id = 567;
UPDATE exercises SET name = 'wspomagane rozciąganie pośladków i mięśnia piriformis na leżąco' WHERE exercise_id = 568;
UPDATE exercises SET name = 'rozciąganie mięśnia biodrowego na piłce do ćwiczeń' WHERE exercise_id = 602;
UPDATE exercises SET name = 'ćwiczenie na jednej nodze na piłce do ćwiczeń w pozycji leżącej z obrotem dolnej części ciała' WHERE exercise_id = 607;
UPDATE exercises SET name = 'ćwiczenie na jednej nodze z przekątnym kopniakiem i skrętem uda na piłce do ćwiczeń' WHERE exercise_id = 608;
UPDATE exercises SET name = 'odwrotny hiper wyprostowania (na piłce stabilizującej)' WHERE exercise_id = 618;
UPDATE exercises SET name = 'wyprost bioder opaską' WHERE exercise_id = 625;
UPDATE exercises SET name = 'unoszenie bioder opaską' WHERE exercise_id = 634;
UPDATE exercises SET name = 'unoszenie bioder leżąc opaską z wewnętrznym obracaniem uda' WHERE exercise_id = 639;
UPDATE exercises SET name = 'przeciągnięcie opaską' WHERE exercise_id = 646;
UPDATE exercises SET name = 'unoszenie bioder w pozycji siedzącej opaską' WHERE exercise_id = 650;
UPDATE exercises SET name = 'przysiad z opaską' WHERE exercise_id = 658;
UPDATE exercises SET name = 'przysiad z opaską z wiosłowaniem' WHERE exercise_id = 659;
UPDATE exercises SET name = 'wchodzenie na step z opaską' WHERE exercise_id = 663;
UPDATE exercises SET name = 'wyprost nóg z opaską' WHERE exercise_id = 664;
UPDATE exercises SET name = 'prosty wyprost nóg z opaską' WHERE exercise_id = 665;
UPDATE exercises SET name = ' barbell clean-grip front squat' WHERE exercise_id = 682;
UPDATE exercises SET name = 'przysiad na klatkę piersiową ze sztangą w uchwycie czystym' WHERE exercise_id = 685;
UPDATE exercises SET name = 'martwy ciąg ze sztangą' WHERE exercise_id = 694;
UPDATE exercises SET name = 'przysiad na klatkę piersiową ze sztangą' WHERE exercise_id = 697;
UPDATE exercises SET name = 'przysiad na klatkę piersiową ze sztangą z przodu' WHERE exercise_id = 698;
UPDATE exercises SET name = 'przysiad pełny ze sztangą' WHERE exercise_id = 699;
UPDATE exercises SET name = 'przysiad pełny ze sztangą (widok z tyłu)' WHERE exercise_id = 700;
UPDATE exercises SET name = 'przysiad pełny ze sztangą (widok z boku)' WHERE exercise_id = 852;
UPDATE exercises SET name = 'przysiad z hantlami na ławce' WHERE exercise_id = 863;
UPDATE exercises SET name = 'drzazga hantlami' WHERE exercise_id = 1157;
UPDATE exercises SET name = 'jednonożny przysiad na maszynie pochyłej pod kątem 45 stopni' WHERE exercise_id = 1159;
UPDATE exercises SET name = 'przysiad na maszynie pochyłej pod kątem 45 stopni' WHERE exercise_id = 1160;
UPDATE exercises SET name = 'przysiad na maszynie pochyłej pod kątem 45 stopni (widok z tyłu)' WHERE exercise_id = 1161;
UPDATE exercises SET name = 'przysiad na maszynie pochyłej pod kątem 45 stopni (widok z boku)' WHERE exercise_id = 1162;
UPDATE exercises SET name = 'przysiad na maszynie pochyłej pod kątem 45 stopni ze sztangą szeroko' WHERE exercise_id = 1164;
UPDATE exercises SET name = 'przysiad hack na maszynie bliżej ciała' WHERE exercise_id = 1166;
UPDATE exercises SET name = 'przysiad hack na maszynie' WHERE exercise_id = 1168;
UPDATE exercises SET name = 'leżący przysiad na maszynie' WHERE exercise_id = 1187;
UPDATE exercises SET name = 'przysiad z kettlebellem w dłoniach' WHERE exercise_id = 1188;
UPDATE exercises SET name = 'wykroki z kettlebellem' WHERE exercise_id = 1190;
UPDATE exercises SET name = 'pistolet z kettlebellem' WHERE exercise_id = 1199;
UPDATE exercises SET name = 'machanie kettlebellem' WHERE exercise_id = 1205;
UPDATE exercises SET name = 'podnoszenie kettlebella w stylu tureckiego wstawania (w pozycji przysiadu)' WHERE exercise_id = 1207;
UPDATE exercises SET name = 'przysiady kozackie z obciążeniem (mężczyzna)' WHERE exercise_id = 1217;
UPDATE exercises SET name = 'wykroki z obciążeniem i machaniem' WHERE exercise_id = 1227;
UPDATE exercises SET name = 'przysiad z obciążeniem' WHERE exercise_id = 1240;
UPDATE exercises SET name = 'wykrok z obciążeniem i skrętem' WHERE exercise_id = 1244;
UPDATE exercises SET name = 'unoszenie bioder na kolanach z opaską oporową (kobieta)' WHERE exercise_id = 1253;
UPDATE exercises SET name = 'rozciąganie bioder na wałku' WHERE exercise_id = 1262;
UPDATE exercises SET name = 'rozciąganie bioder na wałku' WHERE exercise_id = 1263;
UPDATE exercises SET name = 'dzień dobry na maszynie Smitha z ugiętymi kolanami' WHERE exercise_id = 1273;
UPDATE exercises SET name = 'deadlift na maszynie Smitha' WHERE exercise_id = 1277;
UPDATE exercises SET name = 'przysiad na maszynie Smitha (czysty uchwyt)' WHERE exercise_id = 1280;
UPDATE exercises SET name = 'przysiad pełny na maszynie Smitha' WHERE exercise_id = 1281;
UPDATE exercises SET name = 'przysiad hack na maszynie Smitha' WHERE exercise_id = 1282;
UPDATE exercises SET name = 'prasa nóg na maszynie Smitha' WHERE exercise_id = 1287;
UPDATE exercises SET name = 'przysiad nisko na maszynie Smitha' WHERE exercise_id = 1288;
UPDATE exercises SET name = 'rzut oponą' WHERE exercise_id = 1321;
UPDATE exercises SET name = 'deadlift na drążku pułapkowym' WHERE exercise_id = 1322;

