UPDATE exercises SET name = 'lewy sierpowy. boks' WHERE exercise_id = 161;
UPDATE exercises SET name = 'rozciąganie mięśnia naramiennego tylnego' WHERE exercise_id = 218;
UPDATE exercises SET name = 'zmiennie wyciskanie ramion na wyciągu' WHERE exercise_id = 327;
UPDATE exercises SET name = 'zmiennie unoszenie ramion na wyciągu w przeciwnym kierunku' WHERE exercise_id = 336;
UPDATE exercises SET name = 'zmiennie unoszenie ramion na wyciągu do przodu' WHERE exercise_id = 346;
UPDATE exercises SET name = 'podnoszenie boczne na dźwigni' WHERE exercise_id = 515;
UPDATE exercises SET name = 'wyciskanie na dźwigni wojskowe' WHERE exercise_id = 519;
UPDATE exercises SET name = 'zmiennie wyciskanie na dźwigni jednoręcz' WHERE exercise_id = 523;
UPDATE exercises SET name = 'podnoszenie ramion na opasce oporowej w przód' WHERE exercise_id = 632;
UPDATE exercises SET name = 'podnoszenie ramion na opasce oporowej w przód' WHERE exercise_id = 633;
UPDATE exercises SET name = 'zmiennie unoszenie ramion na opasce oporowej' WHERE exercise_id = 648;
UPDATE exercises SET name = 'podnoszenie ramion sztangą do przodu' WHERE exercise_id = 695;
UPDATE exercises SET name = 'zmiennie rwanie jednoręcz sztangą' WHERE exercise_id = 731;
UPDATE exercises SET name = 'unoszenie mięśnia naramiennego tylnego sztangą' WHERE exercise_id = 744;
UPDATE exercises SET name = 'pociąganie sztangą do tyłu mięśnia naramiennego tylnego' WHERE exercise_id = 745;
UPDATE exercises SET name = 'siedzące wyciskanie za głowę na maszynie militarny press' WHERE exercise_id = 761;
UPDATE exercises SET name = 'tańczenie z linami' WHERE exercise_id = 828;
UPDATE exercises SET name = 'zmiennie wyciskanie bokiem z hantlami' WHERE exercise_id = 844;
UPDATE exercises SET name = 'arnold press z hantlami' WHERE exercise_id = 847;
UPDATE exercises SET name = 'arnold press z hantlami w wersji 2' WHERE exercise_id = 848;
UPDATE exercises SET name = 'antygrawitacyjne wyciskanie na EZ-sztandze' WHERE exercise_id = 1138;
UPDATE exercises SET name = 'zmiennie wyciskanie kettlebellem' WHERE exercise_id = 1173;
UPDATE exercises SET name = 'arnold press kettlebellem' WHERE exercise_id = 1177;
UPDATE exercises SET name = 'dwuręczny rwanie kettlebellem' WHERE exercise_id = 1181;
UPDATE exercises SET name = 'dwuręczne wyciskanie kettlebellem' WHERE exercise_id = 1182;
UPDATE exercises SET name = 'dwuręczne rwanie kettlebellem' WHERE exercise_id = 1183;
UPDATE exercises SET name = 'jednoręczne podciągnięcie i szarża kettlebellem' WHERE exercise_id = 1191;
UPDATE exercises SET name = 'podnoszenie ramion z obciążeniem' WHERE exercise_id = 1223;
UPDATE exercises SET name = 'wyciskanie siedzące z obciążeniem na kolana z machaniem' WHERE exercise_id = 1226;
UPDATE exercises SET name = 'podnoszenie ramion z okrężnymi ruchami' WHERE exercise_id = 1233;
UPDATE exercises SET name = 'wyciskanie ramion na opasce oporowej w pozycji siedzącej' WHERE exercise_id = 1258;
UPDATE exercises SET name = 'wyciskanie za kark na maszynie Smitha' WHERE exercise_id = 1271;
UPDATE exercises SET name = 'pociąganie mięśnia naramiennego tylnego na maszynie Smitha' WHERE exercise_id = 1296;
UPDATE exercises SET name = 'wyciskanie ramion na maszynie Smitha' WHERE exercise_id = 1302;
UPDATE exercises SET name = 'rozciąganie mięśnia lędźwiowego na maszynie Smitha' WHERE exercise_id = 1304;

