UPDATE exercises SET name = 'Ośmiornica' WHERE exercise_id = 4;
UPDATE exercises SET name = 'Skok wstecz' WHERE exercise_id = 17;
UPDATE exercises SET name = 'Deska do równowagi' WHERE exercise_id = 18;
UPDATE exercises SET name = 'Wyprostowana noga na krześle' WHERE exercise_id = 52;
UPDATE exercises SET name = 'Skok w przód' WHERE exercise_id = 89;
UPDATE exercises SET name = 'Rozciąganie mięśni czworogłowych na boku' WHERE exercise_id = 168;
UPDATE exercises SET name = 'Mięśnie czworogłowe' WHERE exercise_id = 213;
UPDATE exercises SET name = 'Szybkie kroki v. 2' WHERE exercise_id = 215;
UPDATE exercises SET name = 'Knebelowy przysiad' WHERE exercise_id = 267;
UPDATE exercises SET name = 'Przysiady na podwyższeniu' WHERE exercise_id = 277;
UPDATE exercises SET name = 'Przysiady z unoszeniem nad głowę' WHERE exercise_id = 278;
UPDATE exercises SET name = 'Przysiady z unoszeniem nad głowę z obracaniem' WHERE exercise_id = 279;
UPDATE exercises SET name = 'Podwieszany przysiad z podziałem' WHERE exercise_id = 297;
UPDATE exercises SET name = 'Przemienna naciskowa noga na maszynie' WHERE exercise_id = 491;
UPDATE exercises SET name = 'Noga na maszynie' WHERE exercise_id = 516;
UPDATE exercises SET name = 'Wspomagane rozciąganie mięśni czworogłowych na brzuchu' WHERE exercise_id = 572;
UPDATE exercises SET name = 'Opaska na jedną rękę w jedno nogi przysiady z podziałem' WHERE exercise_id = 642;
UPDATE exercises SET name = 'Opaska na jedną nogę przysiady z podziałem' WHERE exercise_id = 657;
UPDATE exercises SET name = 'Przysiady na ławce z sztangą' WHERE exercise_id = 675;
UPDATE exercises SET name = 'Przysiady na ławce' WHERE exercise_id = 677;
UPDATE exercises SET name = 'Podrzut sztangi i wyciskanie' WHERE exercise_id = 681;
UPDATE exercises SET name = 'Przysiady na jednej nodze ze sztangą' WHERE exercise_id = 732;
UPDATE exercises SET name = 'Przysiady z nad głowę ze sztangą' WHERE exercise_id = 733;
UPDATE exercises SET name = 'Przysiady boczne ze sztangą' WHERE exercise_id = 773;
UPDATE exercises SET name = 'Przysiady boczne ze sztangą v. 2' WHERE exercise_id = 774;
UPDATE exercises SET name = 'Przysiady na jednej nodze ze sztangą' WHERE exercise_id = 776;
UPDATE exercises SET name = 'Przysiady z podziałem ze sztangą v. 2' WHERE exercise_id = 781;
UPDATE exercises SET name = 'Przysiady ze sztangą (na kolanach)' WHERE exercise_id = 782;
UPDATE exercises SET name = 'Skok przysiad z krokiem w tył' WHERE exercise_id = 783;
UPDATE exercises SET name = 'Przysiady szerokie ze sztangą' WHERE exercise_id = 810;
UPDATE exercises SET name = 'Podciągnięcie na wysokość' WHERE exercise_id = 825;
UPDATE exercises SET name = 'Przysiad olimpijski' WHERE exercise_id = 826;
UPDATE exercises SET name = 'Rozciąganie mięśni biodrowo-lędźwiowych i czworogłowych dla zaawansowanych' WHERE exercise_id = 830;
UPDATE exercises SET name = 'Przysiad z hantlami' WHERE exercise_id = 889;
UPDATE exercises SET name = 'Przysiady na jednej nodze ze sztangą' WHERE exercise_id = 1075;
UPDATE exercises SET name = 'Skok na schodach z hantlami' WHERE exercise_id = 1105;
UPDATE exercises SET name = 'Podciągnięcie na schodach ze sztangą' WHERE exercise_id = 1106;
UPDATE exercises SET name = 'Przysiady z podparciem hantli' WHERE exercise_id = 1111;
UPDATE exercises SET name = 'Marsz farmera' WHERE exercise_id = 1127;
UPDATE exercises SET name = 'Obciążone przysiady kneblowe' WHERE exercise_id = 1239;
UPDATE exercises SET name = 'Przysiady na bosu' WHERE exercise_id = 1252;
UPDATE exercises SET name = 'Wyciąganie nogi na maszynie z opaską oporową' WHERE exercise_id = 1254;
UPDATE exercises SET name = 'Przysiady na krześle Smitha' WHERE exercise_id = 1275;
UPDATE exercises SET name = 'Jednonoga noga na krześle Smitha' WHERE exercise_id = 1306;
