UPDATE exercises SET name = 'Brzuszki 3/4' WHERE exercise_id = 1;
UPDATE exercises SET name = 'Skłon boczny pod kątem 45°' WHERE exercise_id = 2;
UPDATE exercises SET name = 'Rower powietrzny' WHERE exercise_id = 3;
UPDATE exercises SET name = 'Naprzemienne dotykanie pięt' WHERE exercise_id = 5;
UPDATE exercises SET name = 'Wiszące unoszenie nóg ze zgiętymi kolanami' WHERE exercise_id = 9;
UPDATE exercises SET name = 'Wiszące unoszenie prostych nóg' WHERE exercise_id = 10;
UPDATE exercises SET name = 'Pełne brzuszki z rękami nad głową (dla mężczyzn)' WHERE exercise_id = 12;
UPDATE exercises SET name = 'Pochylony boczny plank' WHERE exercise_id = 31;
UPDATE exercises SET name = 'Podnoszenie miednicy w górę' WHERE exercise_id = 43;
UPDATE exercises SET name = 'Mostek  wspinacz górski (krzyżowy)' WHERE exercise_id = 45;
UPDATE exercises SET name = 'Podnoszenie pośladków' WHERE exercise_id = 47;
UPDATE exercises SET name = 'Unoszenie prostych nóg na krześle kapitańskim' WHERE exercise_id = 51;
UPDATE exercises SET name = 'Kokony' WHERE exercise_id = 66;
UPDATE exercises SET name = 'Skłon kraba z dotknięciem palców' WHERE exercise_id = 67;
UPDATE exercises SET name = 'Brzuszki skośne' WHERE exercise_id = 68;
UPDATE exercises SET name = 'Brzuszki z rękami nad głową' WHERE exercise_id = 69;
UPDATE exercises SET name = 'Brzuszki na podłodze' WHERE exercise_id = 70;
UPDATE exercises SET name = 'Zwijanie się' WHERE exercise_id = 71;
UPDATE exercises SET name = 'Martwy owad' WHERE exercise_id = 73;
UPDATE exercises SET name = 'Brzuszki na ławce ukośnej' WHERE exercise_id = 74;
UPDATE exercises SET name = 'Wznosy tułowia na ławce ukośnej' WHERE exercise_id = 76;
UPDATE exercises SET name = 'Łokieć do kolana' WHERE exercise_id = 83;
UPDATE exercises SET name = 'Flaga' WHERE exercise_id = 85;
UPDATE exercises SET name = 'Unoszenie tułowia z ugiętymi nogami' WHERE exercise_id = 86;
UPDATE exercises SET name = 'Unoszenie tułowia z prostymi rękami' WHERE exercise_id = 87;
UPDATE exercises SET name = 'Brzuszki żabki' WHERE exercise_id = 91;
UPDATE exercises SET name = 'Plank żabki' WHERE exercise_id = 92;
UPDATE exercises SET name = 'Dźwignia przednia' WHERE exercise_id = 93;
UPDATE exercises SET name = 'Plank przedni ze skrętem' WHERE exercise_id = 95;
UPDATE exercises SET name = 'Pełny maltańczyk' WHERE exercise_id = 96;
UPDATE exercises SET name = 'Pełny plank' WHERE exercise_id = 97;
UPDATE exercises SET name = 'Podciąganie goryla' WHERE exercise_id = 103;
UPDATE exercises SET name = 'Brzuszki krocza' WHERE exercise_id = 104;
UPDATE exercises SET name = 'Półbrzuszki (dla mężczyzn)' WHERE exercise_id = 106;
UPDATE exercises SET name = 'Wiszące unoszenie nóg w biodrach' WHERE exercise_id = 112;
UPDATE exercises SET name = 'Wiszące unoszenie nóg' WHERE exercise_id = 113;
UPDATE exercises SET name = 'Wiszące unoszenie kolan na boki' WHERE exercise_id = 114;
UPDATE exercises SET name = 'Wiszący pike' WHERE exercise_id = 115;
UPDATE exercises SET name = 'Wiszące unoszenie prostych nóg w biodrach' WHERE exercise_id = 116;
UPDATE exercises SET name = 'Wiszące unoszenie prostych nóg' WHERE exercise_id = 117;
UPDATE exercises SET name = 'Wiszące skręcone unoszenie prostych nóg' WHERE exercise_id = 118;
UPDATE exercises SET name = 'Unoszenie bioder (kolana zgięte)' WHERE exercise_id = 120;
UPDATE exercises SET name = 'Robak' WHERE exercise_id = 125;
UPDATE exercises SET name = 'Robak wersja 2' WHERE exercise_id = 126;
UPDATE exercises SET name = 'Unoszenie nóg w biodrach na ławce ukośnej (nogi proste)' WHERE exercise_id = 128;
UPDATE exercises SET name = 'Skrętne wznosy tułowia na ławce ukośnej' WHERE exercise_id = 134;
UPDATE exercises SET name = 'Brzuszki scyzoryk' WHERE exercise_id = 147;
UPDATE exercises SET name = 'Brzuszki Jandy' WHERE exercise_id = 148;
UPDATE exercises SET name = 'Brzuszki z dotykiem kolan' WHERE exercise_id = 153;
UPDATE exercises SET name = 'Klęczący plank z dotykiem ramienia (dla mężczyzn)' WHERE exercise_id = 155;
