UPDATE exercises SET name = 'modyfikowana pompka na obniżanie ramion' WHERE exercise_id = 175;
UPDATE exercises SET name = 'rozciąganie nadgarstków na boku' WHERE exercise_id = 260;
UPDATE exercises SET name = 'kręgi nadgarstków' WHERE exercise_id = 325;
UPDATE exercises SET name = 'odwrotne uginanie nadgarstków na wyciągu' WHERE exercise_id = 413;
UPDATE exercises SET name = 'odwrotne uginanie nadgarstków na wyciągu stojąc tyłem' WHERE exercise_id = 445;
UPDATE exercises SET name = 'uginanie nadgarstków na wyciągu' WHERE exercise_id = 481;
UPDATE exercises SET name = 'sprężynowy uchwyt dźwigni' WHERE exercise_id = 506;
UPDATE exercises SET name = 'odwrotne uginanie nadgarstków na opasce oporowej' WHERE exercise_id = 649;
UPDATE exercises SET name = 'uginanie nadgarstków na opasce oporowej' WHERE exercise_id = 672;
UPDATE exercises SET name = 'uginanie nadgarstków sztangą łamaną nad ławką' WHERE exercise_id = 734;
UPDATE exercises SET name = 'uginanie nadgarstków sztangą nad ławką' WHERE exercise_id = 735;
UPDATE exercises SET name = 'odwrotne uginanie nadgarstków sztangą w wersji 2' WHERE exercise_id = 748;
UPDATE exercises SET name = 'odwrotne uginanie nadgarstków sztangą' WHERE exercise_id = 757;
UPDATE exercises SET name = 'odwrotne uginanie nadgarstków sztangą stojąc tyłem' WHERE exercise_id = 785;
UPDATE exercises SET name = 'uginanie nadgarstków sztangą' WHERE exercise_id = 812;
UPDATE exercises SET name = 'uginanie nadgarstków sztangą w wersji 2' WHERE exercise_id = 813;
UPDATE exercises SET name = 'uginanie palców' WHERE exercise_id = 816;
UPDATE exercises SET name = 'uginanie palców z hantlami' WHERE exercise_id = 882;
UPDATE exercises SET name = 'odwrócone uginanie nadgarstków z hantlami na leżąco' WHERE exercise_id = 947;
UPDATE exercises SET name = 'odwrócone uginanie nadgarstków z hantlami na podłodze' WHERE exercise_id = 948;
UPDATE exercises SET name = 'odwrócone wyprostowanie nadgarstków z hantlami na leżąco' WHERE exercise_id = 953;
UPDATE exercises SET name = 'odwrócone wyprostowanie nadgarstków z hantlami na podłodze' WHERE exercise_id = 954;
UPDATE exercises SET name = 'odwrotne uginanie nadgarstka jednorącz z hantlą' WHERE exercise_id = 977;
UPDATE exercises SET name = 'uginanie nadgarstka jednorącz siedząc w pozycji neutralnej' WHERE exercise_id = 984;
UPDATE exercises SET name = 'uginanie nadgarstka jednorącz z hantlą' WHERE exercise_id = 992;
UPDATE exercises SET name = 'odwrotne uginanie nadgarstka jednorącz z hantlą na ławce' WHERE exercise_id = 997;
UPDATE exercises SET name = 'uginanie nadgarstka jednorącz z hantlą na ławce' WHERE exercise_id = 998;
UPDATE exercises SET name = 'odwrotne uginanie nadgarstków z hantlą na ławce' WHERE exercise_id = 999;
UPDATE exercises SET name = 'uginanie nadgarstków z hantlą na ławce' WHERE exercise_id = 1000;
UPDATE exercises SET name = 'odwrotne uginanie nadgarstków z hantlami' WHERE exercise_id = 1030;
UPDATE exercises SET name = 'uginanie nadgarstków jednorącz w pozycji siedzącej' WHERE exercise_id = 1056;
UPDATE exercises SET name = 'uginanie nadgarstków z hantlami w pozycji dłoni ku górze' WHERE exercise_id = 1060;
UPDATE exercises SET name = 'zmiennie podnoszenie kettlebellem na zmianę' WHERE exercise_id = 1172;
UPDATE exercises SET name = 'uginanie nadgarstków z obciążeniem na stojąco' WHERE exercise_id = 1242;
UPDATE exercises SET name = 'wałek na nadgarstki' WHERE exercise_id = 1249;
UPDATE exercises SET name = 'uginanie nadgarstków na maszynie Smitha' WHERE exercise_id = 1303;
UPDATE exercises SET name = 'uginanie nadgarstków na maszynie Smitha stojąc tyłem' WHERE exercise_id = 1309;

