UPDATE exercises SET name = 'obrót judo na wyciągu' WHERE exercise_id = 359;
UPDATE exercises SET name = 'brzuszki klęczące na wyciągu' WHERE exercise_id = 361;
UPDATE exercises SET name = 'odwrócone brzuszki na wyciągu' WHERE exercise_id = 408;
UPDATE exercises SET name = 'rosyjskie skręty na wyciągu (na piłce stabilizacyjnej)' WHERE exercise_id = 425;
UPDATE exercises SET name = 'brzuszki siedzące na wyciągu' WHERE exercise_id = 427;
UPDATE exercises SET name = 'skręty siedzące na wyciągu' WHERE exercise_id = 436;
UPDATE exercises SET name = 'boczne skłony na wyciągu' WHERE exercise_id = 440;
UPDATE exercises SET name = 'boczne skłony z brzuszkami na wyciągu (na piłce bosu)' WHERE exercise_id = 441;
UPDATE exercises SET name = 'boczne brzuszki na wyciągu' WHERE exercise_id = 442;
UPDATE exercises SET name = 'brzuszki stojące na wyciągu' WHERE exercise_id = 448;
UPDATE exercises SET name = 'brzuszki stojące na wyciągu (z liny)' WHERE exercise_id = 449;
UPDATE exercises SET name = 'unoszenie stojące na wyciągu' WHERE exercise_id = 453;
UPDATE exercises SET name = 'odwrócone brzuszki z podciągnięciem na wyciągu' WHERE exercise_id = 470;
UPDATE exercises SET name = 'skręt na wyciągu' WHERE exercise_id = 471;
UPDATE exercises SET name = 'skręt na wyciągu (góra-dół) ' WHERE exercise_id = 472;
UPDATE exercises SET name = 'skręt klęczący na dźwigni' WHERE exercise_id = 514;
UPDATE exercises SET name = 'brzuszki siedzące na dźwigni' WHERE exercise_id = 536;
UPDATE exercises SET name = 'brzuszki siedzące na dźwigni (z oparciem na klatkę piersiową)' WHERE exercise_id = 537;
UPDATE exercises SET name = 'brzuszki siedzące na dźwigni wersja 2' WHERE exercise_id = 538;
UPDATE exercises SET name = 'brzuszki siedzące z unoszeniem nóg na dźwigni' WHERE exercise_id = 545;
UPDATE exercises SET name = 'wspomagane unoszenie kolan w zwisie' WHERE exercise_id = 564;
UPDATE exercises SET name = 'wspomagane unoszenie kolan w zwisie z rzutem w dół' WHERE exercise_id = 565;
UPDATE exercises SET name = 'wspomagane unoszenie leżących nóg z bocznym rzutem w dół' WHERE exercise_id = 569;
UPDATE exercises SET name = 'wspomagane unoszenie leżących nóg z rzutem w dół' WHERE exercise_id = 570;
UPDATE exercises SET name = 'wspomagane rozciąganie prostowników ud w pozycji leżącej' WHERE exercise_id = 573;
UPDATE exercises SET name = 'wspomagane brzuszki' WHERE exercise_id = 576;
UPDATE exercises SET name = 'wspomagany ruch rosyjskiego skrętu' WHERE exercise_id = 579;
UPDATE exercises SET name = 'jednoręczny slam (z piłką lekarską)' WHERE exercise_id = 589;
UPDATE exercises SET name = 'brzuszki (na piłce stabilizacyjnej)' WHERE exercise_id = 594;
UPDATE exercises SET name = 'brzuszki (na piłce stabilizacyjnej- ręce proste) ' WHERE exercise_id = 595;
UPDATE exercises SET name = 'skręt w pozycji leżącej na piłce stabilizacyjnej' WHERE exercise_id = 614;
UPDATE exercises SET name = 'przyciąganie (na piłce stabilizacyjnej)' WHERE exercise_id = 615;
UPDATE exercises SET name = 'brzuszki na piłce stabilizacyjnej (pełny zakres- ręce za głową)' WHERE exercise_id = 619;
UPDATE exercises SET name = 'naprzemienny v-up z taśmą ' WHERE exercise_id = 621;
UPDATE exercises SET name = 'rozciąganie kółka z taśmą' WHERE exercise_id = 623;
UPDATE exercises SET name = 'brzuszki rowerowe z taśmą' WHERE exercise_id = 626;
UPDATE exercises SET name = 'poziome przyciąganie pallofa z taśmą' WHERE exercise_id = 635;
UPDATE exercises SET name = 'brzuszki scyzoryk z taśmą' WHERE exercise_id = 636;
UPDATE exercises SET name = 'klęczące skrętne brzuszki z taśmą' WHERE exercise_id = 638;
UPDATE exercises SET name = 'unoszenie prostych nóg leżąc z taśmą' WHERE exercise_id = 640;
UPDATE exercises SET name = 'wyciskanie brzuszków z taśmą' WHERE exercise_id = 647;
UPDATE exercises SET name = 'skręty siedzące z taśmą' WHERE exercise_id = 651;
UPDATE exercises SET name = 'brzuszki stojące z taśmą' WHERE exercise_id = 660;
UPDATE exercises SET name = 'stojące skrętne brzuszki z taśmą' WHERE exercise_id = 662;
UPDATE exercises SET name = 'v-up z taśmą ' WHERE exercise_id = 670;
UPDATE exercises SET name = 'pionowe przyciąganie pallofa z taśmą' WHERE exercise_id = 671;
UPDATE exercises SET name = 'brzuszki z wyciskaniem sztangi' WHERE exercise_id = 739;
UPDATE exercises SET name = 'rozciąganie kółka ze sztangą' WHERE exercise_id = 758;
UPDATE exercises SET name = 'rozciąganie kółka ze sztangi z ławki' WHERE exercise_id = 759;
UPDATE exercises SET name = 'skręty siedzące ze sztangą' WHERE exercise_id = 770;
UPDATE exercises SET name = 'boczne skłony ze sztangą wersja 2' WHERE exercise_id = 772;
UPDATE exercises SET name = 'naprzemienne unoszenie nóg siedząc ze sztangą' WHERE exercise_id = 777;
UPDATE exercises SET name = 'naprzemienne unoszenie nóg siedząc ze sztangą (dla kobiet)' WHERE exercise_id = 778;
UPDATE exercises SET name = 'rozciąganie kółka do brzuszków stojąc ze sztangą' WHERE exercise_id = 784;
UPDATE exercises SET name = 'skręty stojące ze sztangą' WHERE exercise_id = 796;
UPDATE exercises SET name = 'landmine 180' WHERE exercise_id = 820;
UPDATE exercises SET name = 'boczne skłony z hantlami' WHERE exercise_id = 1068;
UPDATE exercises SET name = 'rzucacz zaklęć' WHERE exercise_id = 1131;
UPDATE exercises SET name = 'zaawansowany wiatrak kettlebell' WHERE exercise_id = 1171;
UPDATE exercises SET name = 'zgięte wyciskanie kettlebell' WHERE exercise_id = 1178;
UPDATE exercises SET name = 'podwójny wiatrak kettlebell' WHERE exercise_id = 1184;
UPDATE exercises SET name = 'ósemka kettlebell' WHERE exercise_id = 1186;
UPDATE exercises SET name = 'wiatrak kettlebell' WHERE exercise_id = 1211;
UPDATE exercises SET name = 'podnoszenie Otisa' WHERE exercise_id = 1214;
UPDATE exercises SET name = 'obciążone brzuszki' WHERE exercise_id = 1218;
UPDATE exercises SET name = 'obciążone brzuszki na ławce ukośnej' WHERE exercise_id = 1219;
UPDATE exercises SET name = 'obciążony plank przedni' WHERE exercise_id = 1222;
UPDATE exercises SET name = 'obciążone wiszące unoszenie nóg i bioder' WHERE exercise_id = 1224;
UPDATE exercises SET name = 'obciążone brzuszki nad głową (na piłce stabilizacyjnej)' WHERE exercise_id = 1231;
UPDATE exercises SET name = 'obciążony rosyjski skręt' WHERE exercise_id = 1234;
UPDATE exercises SET name = 'obciążony rosyjski skręt (nogi w górze)' WHERE exercise_id = 1235;
UPDATE exercises SET name = 'obciążony rosyjski skręt wersja 2' WHERE exercise_id = 1236;
UPDATE exercises SET name = 'obciążone skręty siedzące (na piłce stabilizacyjnej)' WHERE exercise_id = 1237;
UPDATE exercises SET name = 'obciążone boczne skłony (na piłce stabilizacyjnej)' WHERE exercise_id = 1238;
UPDATE exercises SET name = 'pilarka do ciała' WHERE exercise_id = 1261;
UPDATE exercises SET name = 'odwrócone brzuszki z wałkiem' WHERE exercise_id = 1264;
UPDATE exercises SET name = 'młot ślusarski' WHERE exercise_id = 1269;
UPDATE exercises SET name = 'podnoszenie bioder na maszynie Smitha' WHERE exercise_id = 1283;
UPDATE exercises SET name = 'stojące rozciąganie kółka do brzuszków' WHERE exercise_id = 1318;
UPDATE exercises SET name = 'rozciąganie kółka do brzuszków' WHERE exercise_id = 1319;
