UPDATE exercises SET name = 'Podciąganie łukiem' WHERE exercise_id = 7;
UPDATE exercises SET name = 'Rozciąganie mięśni pleców' WHERE exercise_id = 16;
UPDATE exercises SET name = 'Podciąganie na ławce' WHERE exercise_id = 24;
UPDATE exercises SET name = 'Podciąganie' WHERE exercise_id = 58;
UPDATE exercises SET name = 'Podciąganie w chwycie wąskim' WHERE exercise_id = 63;
UPDATE exercises SET name = 'Podciąganie Gironda' WHERE exercise_id = 99;
UPDATE exercises SET name = 'Skakanie na drążku z uniesieniem klatki piersiowej' WHERE exercise_id = 152;
UPDATE exercises SET name = 'Rozciąganie mięśni grzbietu na kolanach' WHERE exercise_id = 154;
UPDATE exercises SET name = 'Podciąganie w pozycji L' WHERE exercise_id = 158;
UPDATE exercises SET name = 'Podciąganie w chwycie mieszany' WHERE exercise_id = 173;
UPDATE exercises SET name = 'Podciąganie w chwycie odwrotnym' WHERE exercise_id = 326;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej w chwycie bocznym' WHERE exercise_id = 330;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej z użyciem sztangi' WHERE exercise_id = 335;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej w chwycie krzyżowym' WHERE exercise_id = 357;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej w chwycie od góry' WHERE exercise_id = 364;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej w chwycie liny' WHERE exercise_id = 365;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej z V-paskiem' WHERE exercise_id = 366;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej w chwycie liny i wysunięciem rąk do przodu' WHERE exercise_id = 372;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej w chwycie liny i przysiadzie' WHERE exercise_id = 387;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej na jednej ręce' WHERE exercise_id = 398;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej' WHERE exercise_id = 399;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej z użyciem pro lat bar' WHERE exercise_id = 402;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej (wyciąg prostymi ramionami) v. 2' WHERE exercise_id = 407;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej od tyłu' WHERE exercise_id = 484;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej w pozycji siedzącej z V-paskiem' WHERE exercise_id = 485;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej w pozycji siedzącej z użyciem liny' WHERE exercise_id = 486;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej w pozycji siedzącej z użyciem liny' WHERE exercise_id = 487;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej w ruchu jak w kajaku Thibaudeau' WHERE exercise_id = 493;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej z obrotem' WHERE exercise_id = 503;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej w chwycie dolnym' WHERE exercise_id = 522;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej w odwrotnym chwycie' WHERE exercise_id = 527;
UPDATE exercises SET name = 'Podciąganie na maszynie kablowej za pomocą maszyny do wyciskania pleców' WHERE exercise_id = 528;
UPDATE exercises SET name = 'Rzut i chwyt piłki lekarskiej nad głowę' WHERE exercise_id = 561;
UPDATE exercises SET name = 'Ćwiczenia z piłką lekarską na zmianę ramion' WHERE exercise_id = 580;
UPDATE exercises SET name = 'Rozciąganie mięśni bocznych pleców na piłce ćwiczeń' WHERE exercise_id = 596;
UPDATE exercises SET name = 'Rozciąganie dolnego odcinka pleców na piłce ćwiczeń (piramida)' WHERE exercise_id = 604;
UPDATE exercises SET name = 'Rozciąganie mięśni bocznych pleców na boku w pozycji leżącej' WHERE exercise_id = 605;
UPDATE exercises SET name = 'Wspomagane podciąganie na taśmie' WHERE exercise_id = 606;
UPDATE exercises SET name = 'Wspomagane podciąganie w chwycie bliskim na taśmie' WHERE exercise_id = 622;
UPDATE exercises SET name = 'Wspomagane podciąganie w chwycie bliskim na taśmie z ustabilizowanym oparciem' WHERE exercise_id = 627;
UPDATE exercises SET name = 'Wspomagane podciąganie w chwycie odwrotnym na taśmie' WHERE exercise_id = 630;
UPDATE exercises SET name = 'Wspomagane podciąganie na jednej nodze na taśmie' WHERE exercise_id = 631;
UPDATE exercises SET name = 'Wspomagane podciąganie na taśmie w chwycie odwrotnym' WHERE exercise_id = 637;
UPDATE exercises SET name = 'Podciąganie na sztandze ze zgiętymi ramionami' WHERE exercise_id = 669;
UPDATE exercises SET name = 'Podciąganie z obciążeniem w chwycie wąskim na stojaku do dipów' WHERE exercise_id = 678;
UPDATE exercises SET name = 'Podciąganie z obciążeniem' WHERE exercise_id = 687;
UPDATE exercises SET name = 'Podciąganie z obciążeniem na jednej ręce' WHERE exercise_id = 691;
UPDATE exercises SET name = 'Podciąganie z obciążeniem' WHERE exercise_id = 741;
UPDATE exercises SET name = 'Rozciąganie mięśni bocznych pleców na rolce do masażu' WHERE exercise_id = 742;
UPDATE exercises SET name = ' ez bar lying bent arms pullover' WHERE exercise_id = 1133;
UPDATE exercises SET name = ' weighted close grip chin-up on dip cage' WHERE exercise_id = 1216;
UPDATE exercises SET name = ' weighted muscle up' WHERE exercise_id = 1228;
UPDATE exercises SET name = ' weighted muscle up (on bar)' WHERE exercise_id = 1229;
UPDATE exercises SET name = ' weighted one hand pull up' WHERE exercise_id = 1230;
UPDATE exercises SET name = ' weighted pull-up' WHERE exercise_id = 1232;
UPDATE exercises SET name = ' roller side lat stretch' WHERE exercise_id = 1267;
