UPDATE exercises SET name = 'Pompka łukiem' WHERE exercise_id = 8;
UPDATE exercises SET name = 'Rozciąganie klatki piersiowej i przedniej części barku' WHERE exercise_id = 53;
UPDATE exercises SET name = 'Dipy na klatkę piersiową' WHERE exercise_id = 54;
UPDATE exercises SET name = 'Dipy na klatkę piersiową (na stojaku do dipów i podciągania)' WHERE exercise_id = 55;
UPDATE exercises SET name = 'Dipy na klatkę piersiową na prostej sztandze' WHERE exercise_id = 56;
UPDATE exercises SET name = 'Pompka z dotknięciem klatki (mężczyzna)' WHERE exercise_id = 57;
UPDATE exercises SET name = 'Pompka z klapsami' WHERE exercise_id = 61;
UPDATE exercises SET name = 'Pompka z ruchem zegara' WHERE exercise_id = 62;
UPDATE exercises SET name = 'Pompka na nachyleniu' WHERE exercise_id = 75;
UPDATE exercises SET name = 'Pompka z opadaniem' WHERE exercise_id = 79;
UPDATE exercises SET name = 'Dynamiczne rozciąganie klatki piersiowej (mężczyzna)' WHERE exercise_id = 80;
UPDATE exercises SET name = 'Pompka w pozycji pełnego planża' WHERE exercise_id = 98;
UPDATE exercises SET name = 'Pompka na nachyleniu z wyskokiem' WHERE exercise_id = 129;
UPDATE exercises SET name = 'Wyciskanie sztangi na ławce' WHERE exercise_id = 331;
UPDATE exercises SET name = 'Krzyżowanie kablowe różnych wariantów' WHERE exercise_id = 337;
UPDATE exercises SET name = 'Krzyżowanie kablowe na ławce pochyłej' WHERE exercise_id = 340;
UPDATE exercises SET name = 'Krzyżowanie kablowe jednoręczne na ławce pochyłej' WHERE exercise_id = 341;
UPDATE exercises SET name = 'Krzyżowanie kablowe na ławce pochyłej' WHERE exercise_id = 342;
UPDATE exercises SET name = 'Wyciskanie kablowe na ławce pochyłej' WHERE exercise_id = 353;
UPDATE exercises SET name = 'Wyciskanie kablowe na ławce pochyłej' WHERE exercise_id = 355;
UPDATE exercises SET name = 'Wyciskanie kablowe na stabilizującej piłce' WHERE exercise_id = 356;
UPDATE exercises SET name = 'Krzyżowanie kablowe nisko' WHERE exercise_id = 368;
UPDATE exercises SET name = 'Krzyżowanie kablowe leżąc' WHERE exercise_id = 373;
UPDATE exercises SET name = 'Krzyżowanie kablowe środkowe' WHERE exercise_id = 375;
UPDATE exercises SET name = 'Krzyżowanie kablowe jednoręczne na ławce pochyłej' WHERE exercise_id = 378;
UPDATE exercises SET name = 'Krzyżowanie kablowe jednoręczne na piłce ćwiczeniowej' WHERE exercise_id = 379;
UPDATE exercises SET name = 'Krzyżowanie kablowe jednoręczne na ławce pochyłej na piłce ćwiczeniowej' WHERE exercise_id = 380;
UPDATE exercises SET name = 'Krzyżowanie kablowe jednoręczne na ławce pochyłej' WHERE exercise_id = 381;
UPDATE exercises SET name = 'Wspomagane dipy na klatkę piersiową (na kolanach)' WHERE exercise_id = 483;
UPDATE exercises SET name = 'Wspomagane szerokie dipy na klatkę piersiową (na kolanach)' WHERE exercise_id = 489;
UPDATE exercises SET name = 'Wyciskanie na maszynie w pozycji siedzącej' WHERE exercise_id = 498;
UPDATE exercises SET name = 'Wyciskanie na maszynie w pozycji siedzącej' WHERE exercise_id = 499;
UPDATE exercises SET name = 'Wyciskanie na maszynie na ławce pochyłej' WHERE exercise_id = 501;
UPDATE exercises SET name = 'Wyciskanie na maszynie na ławce pochyłej' WHERE exercise_id = 511;
UPDATE exercises SET name = 'Wyciskanie na maszynie na ławce pochyłej' WHERE exercise_id = 512;
UPDATE exercises SET name = 'Wyciskanie na maszynie na ławce pochyłej' WHERE exercise_id = 540;
UPDATE exercises SET name = 'Wyciskanie na maszynie na ławce pochyłej' WHERE exercise_id = 555;
UPDATE exercises SET name = 'prasa wewnętrzna maszyny' WHERE exercise_id = 560;
UPDATE exercises SET name = 'wsparcie siedzącego rozciągania mięśnia piersiowego z piłką stabilizującą' WHERE exercise_id = 574;
UPDATE exercises SET name = 'rozciąganie klatki piersiowej za głowę' WHERE exercise_id = 578;
UPDATE exercises SET name = 'rzut piłką lekarską na klatkę piersiową' WHERE exercise_id = 581;
UPDATE exercises SET name = 'pchnięcie piłką lekarską z pozycji 3-punktowej' WHERE exercise_id = 582;
UPDATE exercises SET name = 'pchnięcie piłką lekarską wielokrotna odpowiedź' WHERE exercise_id = 583;
UPDATE exercises SET name = 'pchnięcie piłką lekarską pojedyncza odpowiedź' WHERE exercise_id = 584;
UPDATE exercises SET name = 'pchnięcie piłką lekarską z uwolnieniem biegu' WHERE exercise_id = 585;
UPDATE exercises SET name = 'pompka na piłce lekarskiej' WHERE exercise_id = 590;
UPDATE exercises SET name = 'rozciąganie klatki piersiowej na piłce do ćwiczeń' WHERE exercise_id = 593;
UPDATE exercises SET name = 'pompka na piłce do ćwiczeń w pozycji pionowej' WHERE exercise_id = 609;
UPDATE exercises SET name = 'pompka (na piłce stabilizującej)' WHERE exercise_id = 616;
UPDATE exercises SET name = 'pompka (na piłce stabilizującej)' WHERE exercise_id = 617;
UPDATE exercises SET name = 'pchnięcie opaską na ławce' WHERE exercise_id = 624;
UPDATE exercises SET name = 'pchnięcie opaską jednorącz na skrętność klatki piersiowej' WHERE exercise_id = 644;
UPDATE exercises SET name = 'wyciskanie sztangi na ławce' WHERE exercise_id = 676;
UPDATE exercises SET name = 'wyciskanie sztangi na ławce pochylonej' WHERE exercise_id = 686;
UPDATE exercises SET name = 'rozpiętki sztangą na ławce pochylonej' WHERE exercise_id = 689;
UPDATE exercises SET name = 'wyciskanie sztangi szerokim uchwytem na ławce pochylonej' WHERE exercise_id = 690;
UPDATE exercises SET name = 'wznoszenie sztangi przed siebie i rozpiętki' WHERE exercise_id = 696;
UPDATE exercises SET name = '"wyciskanie sztangi na ławce ""krokodyl""' WHERE exercise_id = 705;
UPDATE exercises SET name = 'wyciskanie sztangi na ławce skośnej' WHERE exercise_id = 708;
UPDATE exercises SET name = 'wyciskanie sztangi na ławce pochylonej w uchwycie odwrotnym' WHERE exercise_id = 752;
UPDATE exercises SET name = 'wyciskanie sztangi na ławce skośnej w uchwycie odwrotnym' WHERE exercise_id = 753;
UPDATE exercises SET name = 'wyciskanie sztangi na szerokiej ławce' WHERE exercise_id = 808;
UPDATE exercises SET name = 'wyciskanie sztangi na szerokiej ławce w uchwycie odwrotnym' WHERE exercise_id = 809;
UPDATE exercises SET name = 'rozpiętki na podłodze (ze sztangą)' WHERE exercise_id = 817;
UPDATE exercises SET name = 'pompka na głębokiej pozycji' WHERE exercise_id = 838;
UPDATE exercises SET name = 'rozpiętki hantlami wokół korpusu' WHERE exercise_id = 849;
UPDATE exercises SET name = 'wyciskanie hantli na ławce' WHERE exercise_id = 850;
UPDATE exercises SET name = 'wyciskanie hantli na ławce pochylonej' WHERE exercise_id = 873;
UPDATE exercises SET name = 'rozpiętki hantlami na ławce pochylonej' WHERE exercise_id = 874;
UPDATE exercises SET name = 'wyciskanie hantli na ławce pochylonej w uchwycie młotkowym' WHERE exercise_id = 875;
UPDATE exercises SET name = 'rozpiętki hantlami na ławce pochylonej jednorącz' WHERE exercise_id = 876;
UPDATE exercises SET name = 'rozpiętki hantlami na ławce pochylonej z obrotem' WHERE exercise_id = 881;
UPDATE exercises SET name = 'rower ręczny' WHERE exercise_id = 1170;
UPDATE exercises SET name = 'prasa obciążeniem w zakresie jednej ręki na podłodze z kettlebellem na zmianę' WHERE exercise_id = 1174;
UPDATE exercises SET name = 'prasa obciążeniem w zakresie jednej ręki na podłodze z kettlebellem w rozszerzonym zakresie ruchu' WHERE exercise_id = 1185;
UPDATE exercises SET name = 'prasa obciążeniem jednej ręki na podłodze z kettlebellem' WHERE exercise_id = 1192;
UPDATE exercises SET name = 'plyometryczna pompka z kettlebellem' WHERE exercise_id = 1200;
UPDATE exercises SET name = 'pompka z obciążeniem na opadzie' WHERE exercise_id = 1221;
UPDATE exercises SET name = 'pompka na prostą sztangę z obciążeniem' WHERE exercise_id = 1243;
UPDATE exercises SET name = 'pchnięcie Svenda z obciążeniem' WHERE exercise_id = 1245;
UPDATE exercises SET name = 'pompka na kuli Bosu' WHERE exercise_id = 1250;
UPDATE exercises SET name = 'pompka (na kuli Bosu)' WHERE exercise_id = 1251;
UPDATE exercises SET name = 'wyciskanie na maszynie z opaską oporową w pozycji siedzącej na klatkę piersiową' WHERE exercise_id = 1256;
UPDATE exercises SET name = 'rolka siedząca na fleksorach i depresorach barków' WHERE exercise_id = 1265;
UPDATE exercises SET name = 'rolka siedząca na jednej nodze na fleksorach i depresorach barków' WHERE exercise_id = 1266;
UPDATE exercises SET name = 'wyciskanie na maszynie Smitha' WHERE exercise_id = 1272;
UPDATE exercises SET name = 'wyciskanie na pochyłej maszynie Smitha' WHERE exercise_id = 1278;
UPDATE exercises SET name = 'wyciskanie na pochyłej maszynie Smitha w uchwycie odwrotnym' WHERE exercise_id = 1279;
UPDATE exercises SET name = 'wyciskanie na maszynie Smitha na pochyłej' WHERE exercise_id = 1284;
UPDATE exercises SET name = 'wyciskanie na maszynie Smitha na pochyłej w uchwycie odwrotnym' WHERE exercise_id = 1285;
UPDATE exercises SET name = 'wyciskanie na maszynie Smitha z odwrotną pochyłką i wąskim uchwytem' WHERE exercise_id = 1292;
UPDATE exercises SET name = 'wyciskanie na maszynie Smitha w uchwycie odwrotnym' WHERE exercise_id = 1300;
UPDATE exercises SET name = 'wyciskanie na maszynie Smitha na szerokiej ławce' WHERE exercise_id = 1316;
UPDATE exercises SET name = 'wyciskanie na maszynie Smitha na szerokiej pochyłej ławce' WHERE exercise_id = 1317;

