UPDATE exercises SET name = 'pompka na ławce (z ugiętymi kolanami)' WHERE exercise_id = 21;
UPDATE exercises SET name = 'pompka na ławce na podłodze' WHERE exercise_id = 22;
UPDATE exercises SET name = 'wyciskanie ciała' WHERE exercise_id = 29;
UPDATE exercises SET name = 'extension tricepsa na kolanach z obciążeniem własnego ciała' WHERE exercise_id = 32;
UPDATE exercises SET name = 'zmiennie rozciąganie na triceps na wyciągu' WHERE exercise_id = 328;
UPDATE exercises SET name = 'koncentryczne rozciąganie na triceps na wyciągu (na kolanie)' WHERE exercise_id = 334;
UPDATE exercises SET name = 'wyciąg w górę na wyciągu wysokim nad głową do tricepsa' WHERE exercise_id = 350;
UPDATE exercises SET name = 'pompka na triceps z użyciem wsparcia (na kolanach)' WHERE exercise_id = 488;
UPDATE exercises SET name = 'uginanie tricepsa nad głową na dźwigni z podchwytem' WHERE exercise_id = 524;
UPDATE exercises SET name = 'siedzące oparcie na dźwigni' WHERE exercise_id = 539;
UPDATE exercises SET name = 'extension tricepsa na dźwigni' WHERE exercise_id = 558;
UPDATE exercises SET name = 'extension tricepsa na stojąco z użyciem wsparcia (z ręcznikiem)' WHERE exercise_id = 577;
UPDATE exercises SET name = 'pompka na wąsko z piłką lekarską' WHERE exercise_id = 586;
UPDATE exercises SET name = 'rzuć piłką lekarską w pozycji leżącej na plecach' WHERE exercise_id = 588;
UPDATE exercises SET name = 'pompka na piłce do ćwiczeń' WHERE exercise_id = 601;
UPDATE exercises SET name = 'rozciąganie tricepsa na piłce do ćwiczeń w pozycji siedzącej' WHERE exercise_id = 612;
UPDATE exercises SET name = 'pompka na wąsko na piłce do ćwiczeń' WHERE exercise_id = 613;
UPDATE exercises SET name = 'pompka na wąsko z opaską oporową' WHERE exercise_id = 628;
UPDATE exercises SET name = 'rozciąganie tricepsa na boku z opaską oporową' WHERE exercise_id = 654;
UPDATE exercises SET name = 'wyciskanie na wąsko na ławce' WHERE exercise_id = 683;
UPDATE exercises SET name = 'wyciskanie na wąsko na ławce pochylonej do czoła' WHERE exercise_id = 688;
UPDATE exercises SET name = 'wyciskanie na wąsko na ławce skośnej' WHERE exercise_id = 709;
UPDATE exercises SET name = 'wyciskanie na wąsko na ławce skośnej w uchwycie odwrotnym' WHERE exercise_id = 710;
UPDATE exercises SET name = 'wyciskanie na wąsko hantli' WHERE exercise_id = 864;
UPDATE exercises SET name = 'wyciskanie na wąsko hantli' WHERE exercise_id = 865;
UPDATE exercises SET name = 'wyciskanie na wąsko hantli na ławce pochylonej jednorącz' WHERE exercise_id = 877;
UPDATE exercises SET name = 'uginanie francuskie na EZ-sztandze na piłce do ćwiczeń' WHERE exercise_id = 1132;
UPDATE exercises SET name = 'uginanie tricepsa leżąc na EZ-sztandze z wąskim uchwytem za głowę' WHERE exercise_id = 1134;
UPDATE exercises SET name = 'stanie z EZ-sztangą na wyciskanie w pozycji stojącej' WHERE exercise_id = 1137;
UPDATE exercises SET name = 'extension tricepsa olimpijską sztangą' WHERE exercise_id = 1213;
UPDATE exercises SET name = 'pompka na ławce (z użyciem obciążenia)' WHERE exercise_id = 1215;
UPDATE exercises SET name = 'ergometr narciarski' WHERE exercise_id = 1268;
UPDATE exercises SET name = 'wyciskanie na wąsko na maszynie Smitha' WHERE exercise_id = 1276;
UPDATE exercises SET name = 'wyciskanie na wąsko na maszynie Smitha na ławce pochylonej' WHERE exercise_id = 1290;
UPDATE exercises SET name = 'extension tricepsa na maszynie Smitha na ławce skośnej' WHERE exercise_id = 1291;
