# Generated by Django 4.2.7 on 2024-01-16 01:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                ("client_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("surname", models.TextField()),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("email", models.TextField()),
                ("age", models.IntegerField(blank=True, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("hash_pass", models.CharField(max_length=512)),
            ],
            options={
                "db_table": "clients",
            },
        ),
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                ("equipment_id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.TextField()),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "equipment_type",
            },
        ),
        migrations.CreateModel(
            name="Exercises",
            fields=[
                ("exercise_id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.TextField()),
                ("name", models.TextField()),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="project.equipmenttype",
                    ),
                ),
            ],
            options={
                "db_table": "exercises",
            },
        ),
        migrations.CreateModel(
            name="Gyms",
            fields=[
                ("gym_id", models.AutoField(primary_key=True, serialize=False)),
                ("city", models.TextField()),
                ("postal_code", models.CharField(max_length=20)),
                ("street", models.TextField()),
                ("street_number", models.IntegerField()),
                ("building_number", models.IntegerField(blank=True, null=True)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "db_table": "gyms",
            },
        ),
        migrations.CreateModel(
            name="Managers",
            fields=[
                ("manager_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("surname", models.TextField()),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("email", models.TextField()),
                ("hash_pass", models.CharField(max_length=512)),
            ],
            options={
                "db_table": "managers",
            },
        ),
        migrations.CreateModel(
            name="Trainers",
            fields=[
                ("trainer_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("surname", models.TextField()),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("email", models.TextField()),
                ("hour_salary", models.IntegerField(blank=True, null=True)),
                ("hash_pass", models.CharField(max_length=512)),
                ("info", models.TextField()),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="project.gyms",
                    ),
                ),
            ],
            options={
                "db_table": "trainers",
            },
        ),
        migrations.CreateModel(
            name="TrainingPlans",
            fields=[
                (
                    "training_plan_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("category", models.TextField()),
                ("name", models.TextField()),
                ("time", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "training_plans",
            },
        ),
        migrations.CreateModel(
            name="Trainings",
            fields=[
                ("training_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="project.clients",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="project.trainers",
                    ),
                ),
                (
                    "training_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="project.trainingplans",
                    ),
                ),
            ],
            options={
                "db_table": "trainings",
            },
        ),
        migrations.CreateModel(
            name="Tokens",
            fields=[
                (
                    "key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_tokens",
                        to="project.clients",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_tokens",
                        to="project.managers",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_tokens",
                        to="project.trainers",
                    ),
                ),
            ],
            options={
                "db_table": "tokens",
            },
        ),
        migrations.AddField(
            model_name="gyms",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="project.managers"
            ),
        ),
        migrations.CreateModel(
            name="GymsEquipmentType",
            fields=[
                ("available", models.IntegerField()),
                ("used", models.IntegerField()),
                (
                    "serial_number",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="project.equipmenttype",
                    ),
                ),
                (
                    "gym",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="project.gyms",
                    ),
                ),
            ],
            options={
                "db_table": "gyms_equipment_type",
                "unique_together": {("gym", "equipment")},
            },
        ),
        migrations.CreateModel(
            name="TrainingsExercises",
            fields=[
                (
                    "training",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="project.trainings",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("repeats", models.IntegerField(blank=True, null=True)),
                ("time", models.IntegerField(blank=True, null=True)),
                ("load", models.IntegerField(blank=True, null=True)),
                ("calories", models.IntegerField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="project.exercises",
                    ),
                ),
            ],
            options={
                "db_table": "trainings_exercises",
                "unique_together": {("training", "exercise")},
            },
        ),
        migrations.CreateModel(
            name="ExercisesTrainingPlans",
            fields=[
                (
                    "exercise",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="project.exercises",
                    ),
                ),
                ("repeats", models.IntegerField(blank=True, null=True)),
                ("time", models.IntegerField(blank=True, null=True)),
                ("load", models.IntegerField(blank=True, null=True)),
                (
                    "training_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="project.trainingplans",
                    ),
                ),
            ],
            options={
                "db_table": "exercises_training_plans",
                "unique_together": {("exercise", "training_plan")},
            },
        ),
    ]
