# Generated by Django 4.2.2 on 2024-01-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("project", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="trainingplans", name="category", field=models.TextField()
        ),
        migrations.AlterField(
            model_name="trainingplans", name="name", field=models.TextField()
        ),
    ]
