# Generated by Django 4.2.7 on 2024-01-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_alter_trainingplans_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainings",
            name="end_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainings",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
