# Generated by Django 4.2.7 on 2024-01-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_alter_trainings_end_time_alter_trainings_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainings",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainings",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
